src/LegacyCode/MvcApplication/Controllers/FormationController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Framework;

namespace MvcApplication.Controllers
{
    public class FormationController : Controller
    {
        //
        // GET: /Formation/

        public ActionResult Index(int intId = 1)
        {
                    List<Formation> results = FormationFactory. List(intId) ; 

                    String output = "<h1>Liste des formations</h1><table>";
                    int pourcent = FormationFactory.GetPourcent(intId);
                        
                    output+="<h4>Pourcentage de remplissage : "+pourcent +"</h4>";

                    output+="<tr><td>ID internaute</td><td>ID Formation</td><td> Date Début</td><td> Date Fin</td><td>Ecole"
                            +"</td><td>Lieu</td><td>Specialite</td><td>Diplome</td><td>Obtenu"
                            + "</td><td>Code</td><td>Libelle</td></tr>";
                    foreach(Formation result in results){
                        output+=result;
                    }
                    output+="</table>";
                    this.ViewData["Result"] = output;
                    return View();
        }

        
        // GET: /Formation/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Formation/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                
                AjoutFormationSvc controller = new AjoutFormationSvc();
                SessionContainer scc = new SessionContainer();

                CtrlAttributesEnregistrer attributes = new CtrlAttributesEnregistrer();
                attributes.param_f_formation1_diplome = collection["Diplome"];
                attributes.param_f_formation1_lieu = collection["Lieu"];
                attributes.param_f_niveau_formation = int.Parse(collection["Niveau"]);

                
                controller.DoEnregistrer(scc, attributes);
               
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Formation/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Formation/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Formation/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Formation/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/LegacyCode/MvcApplication/Controllers/FormationsController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Framework;

namespace MvcApplication.Controllers
{
    public class FormationsController : Controller
    {
        //
        // GET: /Formation/

        public ActionResult Index(int intId = 1)
        {
                    List<Formation> results = FormationFactory. List(intId) ; 

                    String output = "<h1>Liste des formations</h1><table>";
                    int pourcent = FormationFactory.GetPourcent(intId);
                        
                    output+="<h4>Pourcentage de remplissage : "+pourcent +"</h4>";

                    output+="<tr><td>ID internaute</td><td>ID Formation</td><td> Date Début</td><td> Date Fin</td><td>Ecole"
                            +"</td><td>Lieu</td><td>Specialite</td><td>Diplome</td><td>Obtenu"
                            + "</td><td>Code</td><td>Libelle</td></tr>";
                    foreach(Formation result in results){
                        output+=result;
                    }
                    output+="</table>";
                    this.ViewData["Result"] = output;
                    return View();
        }

        
        // GET: /Formation/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Formation/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                
                AjoutFormationSvc controller = new AjoutFormationSvc();
                SessionContainer scc = new SessionContainer();

                CtrlAttributesEnregistrer attributes = new CtrlAttributesEnregistrer();
                attributes.param_f_formation1_diplome = collection["Diplome"];
                attributes.param_f_formation1_lieu = collection["Lieu"];
                attributes.param_f_niveau_formation = int.Parse(collection["Niveau"]);

                
                controller.DoEnregistrer(scc, attributes);
               
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Formation/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Formation/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Formation/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Formation/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/LegacyCode/MvcApplication/Views/Formation/Create.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>Creation</title>
    </head>
    <body>
        <div>
            @using(Html.BeginForm("Create","Formation",FormMethod.Post))
            {
               <fieldset>
                Diplome @Html.TextBox("Diplome")<br/>
                Lieu @Html.TextBox("Lieu")<br/>
                   Niveau @Html.DropDownList("Niveau",Enumerable.Range(1,5).Select(r=>new SelectListItem{Value = r.ToString(),Text = r.ToString()}))<br/>
                   <input type="submit"/>
                
               </fieldset> 
            }
        </div>
    </body>
</html>

src/LegacyCode/MvcApplication/Views/Formations/Create.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>Creation</title>
    </head>
    <body>
        <div>
            @using(Html.BeginForm("Create","Formations",FormMethod.Post))
            {
               <fieldset>
                Diplome @Html.TextBox("Diplome")<br/>
                Lieu @Html.TextBox("Lieu")<br/>
                   Niveau @Html.DropDownList("Niveau",Enumerable.Range(1,5).Select(r=>new SelectListItem{Value = r.ToString(),Text = r.ToString()}))<br/>
                   <input type="submit"/>
                
               </fieldset> 
            }
        </div>
    </body>
</html>

src/LegacyCode/MvcApplication/Views/Formations/Index.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>Formation</title>
    </head>
    <body>
        <div>
            @Html.Raw(ViewData["Result"].ToString())  
        </div>
    </body>
</html>

src/LegacyCode/MvcApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>